### ISSUE TITLE
[BUG] 标题 Header头header.put("Connection", "keep-alive,X-F5-Auth-Token")Connection不生效

### ISSUE THREAD

**Issue by shuimuLiu** [woodpecker-framework/woodpecker-framwork-release#15]
## 一、运行环境
* 操作系统： Windows7
* JDK版本：1.8.1_131
* woodpecker-framework版本：1.3.3

## 二、问题描述
Header头header.put("Connection", "keep-alive,X-F5-Auth-Token")Connection不生效
![image](https://user-images.githubusercontent.com/42109695/167759433-411b5360-973a-4f17-8f58-75f4920dc8b2.png)
数据包如下，可以看到Connection的值被自动改为了close
![image](https://user-images.githubusercontent.com/42109695/167759621-4756281c-2ae3-43c8-aeac-52d78197e874.png)
修改客户端的Custom http header也没用
![image](https://user-images.githubusercontent.com/42109695/167759683-ab6da0f3-b799-4a76-a661-7469f9f1b461.png)

## 三、bug产生的原因和建议
可以考虑发送请求的时候对底层HTTP进行反射修改。

**Comment by Pretexts** [comment]
我也遇到了这个问题。

**Comment by kN6jq** [comment]
一样遇到了header   Connection不更新的错误 ，
还有一个bug

使用jsonBody方法传json的时候


![image](https://user-images.githubusercontent.com/27048404/167772665-88dc5a7d-d737-4f99-b0d9-2185def953f7.png)

传出来是这样子
![image](https://user-images.githubusercontent.com/27048404/167772749-49fd11c3-49d6-44e6-9161-4ff0771c7856.png)

**Comment by c0ny1** [comment]
这个是代理到burp被burp修改了。wireshark可以抓到原始包
<img width="957" alt="image" src="https://user-images.githubusercontent.com/15975792/167878635-100f0272-f9d4-499f-85d2-94a6e95286d0.png">

burp要修改下设置

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/15975792/167878780-ea58cfcf-2433-4d13-aede-46a3c01af296.png">

**Comment by shuimuLiu** [comment]
确实，F5的漏洞Header还需要添加Content-Type:application/json，否则还会出现验证错误
![Uploading image.png…]()

**Comment by shuimuLiu** [comment]
确实，F5这个洞还需要添加Content-Type:application/json，不然不会生效
![image](https://user-images.githubusercontent.com/42109695/167887840-6fe5ead7-e10a-4581-81dc-1dc600f33612.png)
