### ISSUE TITLE
这个项目是没人维护了嘛？？？？？

### ISSUE THREAD

**Issue by AhrendsSchmidt** [woodpecker-framework/woodpecker-framwork-release#27]
![image](https://github.com/woodpecker-framework/woodpecker-framework-release/assets/33677393/309af4c4-dbce-4ed6-a70e-75fe2cc8d517)
作者公布的源代码里面就没有这个类，都是接口，没有具体的实现
![image](https://github.com/woodpecker-framework/woodpecker-framework-release/assets/33677393/b4b00f0b-a5c8-4c2a-a924-eda0e6dd7444)
打包出来的jar包里面也没有这个类
![image](https://github.com/woodpecker-framework/woodpecker-framework-release/assets/33677393/4bad67dc-8801-4231-a6cc-fc4865943f21)，既然编译出来用不了，为什么还要在下面写编译方式，这不是误导人嘛，既然东西开源了，就好好做嘛，要不然就别做，别糊弄人

**Comment by Richard-Tang** [comment]
这个是插件的入口类，需要你自己建包和创建类 - -!
